"""rename fan to clean

Revision ID: a93520d18c6f
Revises: d6f36aaa3858
Create Date: 2022-08-12 15:28:34.562463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93520d18c6f'
down_revision = 'd6f36aaa3858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.alter_column('fan', new_column_name='clean')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.alter_column('clean', new_column_name='fan')
    # ### end Alembic commands ###
