"""initial

Revision ID: d6f36aaa3858
Revises: 
Create Date: 2022-08-12 15:02:55.204794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f36aaa3858'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('stat', sa.String(length=2), nullable=True),
    sa.Column('txaddr', sa.String(length=2), nullable=True),
    sa.Column('rxaddr', sa.String(length=2), nullable=True),
    sa.Column('opc1', sa.String(length=2), nullable=True),
    sa.Column('mode', sa.String(length=2), nullable=True),
    sa.Column('opc2', sa.String(length=2), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('rawdata', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('power', sa.String(length=3), nullable=True),
    sa.Column('mode', sa.String(length=9), nullable=True),
    sa.Column('fan', sa.String(length=2), nullable=True),
    sa.Column('fanlv', sa.String(length=4), nullable=True),
    sa.Column('settmp', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('pwrlv1', sa.Integer(), nullable=True),
    sa.Column('pwrlv2', sa.Integer(), nullable=True),
    sa.Column('sens_ta', sa.Integer(), nullable=True),
    sa.Column('sens_tcj', sa.Integer(), nullable=True),
    sa.Column('sens_tc', sa.Integer(), nullable=True),
    sa.Column('sens_te', sa.Integer(), nullable=True),
    sa.Column('sens_to', sa.Integer(), nullable=True),
    sa.Column('sens_td', sa.Integer(), nullable=True),
    sa.Column('sens_ts', sa.Integer(), nullable=True),
    sa.Column('sens_ths', sa.Integer(), nullable=True),
    sa.Column('sens_current', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('packet')
    # ### end Alembic commands ###
